# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GameView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(949, 600)
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tablero = QtWidgets.QTableWidget(self.centralwidget)
        self.tablero.setGeometry(QtCore.QRect(10, 40, 781, 451))
        self.tablero.setRowCount(0)
        self.tablero.setColumnCount(0)
        self.tablero.setObjectName("tablero")
        self.tablero.horizontalHeader().setCascadingSectionResizes(False)
        self.tablero.horizontalHeader().setHighlightSections(False)
        self.tablero.horizontalHeader().setSortIndicatorShown(False)
        self.tablero.horizontalHeader().setStretchLastSection(False)
        self.tablero.verticalHeader().setVisible(True)
        self.tablero.verticalHeader().setCascadingSectionResizes(False)
        self.tablero.verticalHeader().setSortIndicatorShown(False)
        self.tablero.verticalHeader().setStretchLastSection(False)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(200, 510, 71, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 511, 81, 20))
        self.label_2.setObjectName("label_2")
        self.Coordenada_X = QtWidgets.QLineEdit(self.centralwidget)
        self.Coordenada_X.setGeometry(QtCore.QRect(280, 510, 113, 20))
        self.Coordenada_X.setObjectName("Coordenada_X")
        self.Coordenada_Y = QtWidgets.QLineEdit(self.centralwidget)
        self.Coordenada_Y.setGeometry(QtCore.QRect(490, 510, 113, 20))
        self.Coordenada_Y.setObjectName("Coordenada_Y")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(330, 10, 141, 16))
        self.label_3.setObjectName("label_3")
        self.GeneralTimer = QtWidgets.QLabel(self.centralwidget)
        self.GeneralTimer.setGeometry(QtCore.QRect(470, 10, 21, 16))
        self.GeneralTimer.setObjectName("GeneralTimer")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(820, 40, 101, 16))
        self.label_4.setObjectName("label_4")
        self.playerTimer = QtWidgets.QLabel(self.centralwidget)
        self.playerTimer.setGeometry(QtCore.QRect(870, 60, 21, 16))
        self.playerTimer.setObjectName("playerTimer")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(830, 90, 91, 16))
        self.label_5.setObjectName("label_5")
        self.numPiezas = QtWidgets.QLabel(self.centralwidget)
        self.numPiezas.setGeometry(QtCore.QRect(870, 110, 21, 16))
        self.numPiezas.setObjectName("numPiezas")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(840, 140, 71, 16))
        self.label_6.setObjectName("label_6")
        self.terminarButton = QtWidgets.QPushButton(self.centralwidget)
        self.terminarButton.setGeometry(QtCore.QRect(830, 500, 91, 41))
        self.terminarButton.setObjectName("terminarButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(830, 260, 101, 20))
        self.label_7.setObjectName("label_7")
        self.numPiezas_2 = QtWidgets.QLabel(self.centralwidget)
        self.numPiezas_2.setGeometry(QtCore.QRect(870, 280, 21, 16))
        self.numPiezas_2.setObjectName("numPiezas_2")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(850, 170, 71, 61))
        self.image.setText("")
        self.image.setObjectName("image")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 949, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Coordenada X:"))
        self.label_2.setText(_translate("MainWindow", "Coordenada Y:"))
        self.label_3.setText(_translate("MainWindow", "Tiempo De Juego Restante:"))
        self.GeneralTimer.setText(_translate("MainWindow", "0"))
        self.label_4.setText(_translate("MainWindow", "Tu torno termina en:"))
        self.playerTimer.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Piezas Restantes:"))
        self.numPiezas.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Siguiente Pieza:"))
        self.terminarButton.setText(_translate("MainWindow", "Terminar Turno"))
        self.label_7.setText(_translate("MainWindow", "Intentos Restantes:"))
        self.numPiezas_2.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
